name: Release

on:
  push:
    branches:
      - dev

env:
  RELEASE_TAR: ./dist/hugo-geekdoc.tar.gz

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Pack
        run: npm run pack

      - name: Extract release to directory
        run: |
          tar -xf ./dist/hugo-geekdoc.tar.gz -C ./dist; rm ./dist/hugo-geekdoc.tar.gz

      - name: Push to main branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
